export const RAKIT_ICONS = {
  "rk:user": "lucide:user-round", // 用户
  "rk:user-xmark": "lucide:user-round-x", // 用户x
  "rk:user-check": "lucide:user-round-check", // 用户check
  "rk:lock": "gravity-ui:lock", // 密码
  "rk:key": "lucide:key", // 密钥
  "rk:captcha": "gravity-ui:square-brackets-letter-a", // 验证码
  "rk:screen-full": "icon-park-outline:screenshot-one", // 全屏
  "rk:screen-exit": "icon-park-outline:off-screen", // 全屏
  "rk:sun": "lucide:sun", // 白天
  "rk:moon": "lucide:moon", // 夜晚
  "rk:bell": "lucide:bell-ring", // 铃铛/消息
  "rk:workbench": "icon-park-outline:workbench", // 工作台
  "rk:column-3": "lucide:columns-3", // 三列
  "rk:column-todo": "lucide:list-todo", // 设置
  "rk:column-density": "tabler:layout-distribute-horizontal", // 列设置
  "rk:xmark": "gravity-ui:xmark", // 叉号
  "rk:refresh": "gravity-ui:arrow-rotate-right", // 刷新
  "rk:sort-dots": "lucide:grip-vertical", // 排序
  "rk:upload": "lucide:upload", // 上传
  "rk:download": "lucide:download", // 上传
  "rk:export": "lucide:export", // 上传
  "rk:edit": "lucide:edit", // 编辑
  "rk:search": "lucide:search", // 搜索
  "rk:trash": "lucide:trash-2", // 删除
  "rk:plus": "lucide:plus", // 新增
  "rk:recycle": "tabler:recycle", // 回收
  "rk:history": "icon-park-outline:history-query", // 历史
  "rk:menu-left": "line-md:menu-fold-left", // 菜单左折叠
  "rk:menu-right": "line-md:menu-fold-right", // 菜单右折叠
  "rk:setting": "gravity-ui:nut-hex", // 设置
  "rk:logout": "si:sign-out-fill", // 退出
  "rk:play": "gravity-ui:play", // 播放
  "rk:pause": "gravity-ui:pause", // 暂停
  "rk:report": "tabler:report-analytics", // 报告
  "rk:score-100": "fluent:document-100-16-regular", // 100分
  "rk:chevron-up": "lucide:chevron-up", // 向上箭头
  "rk:chevron-down": "lucide:chevron-down", // 向下箭头
  "rk:chevron-left": "lucide:chevron-left", // 向左箭头
  "rk:chevron-right": "lucide:chevron-right", // 向右箭
  "rk:arrow-up": "lucide:arrow-up", // 向上箭头
  "rk:arrow-down": "lucide:arrow-down", // 向下箭头
  "rk:arrow-left": "lucide:arrow-left", // 向左箭头
  "rk:arrow-right": "lucide:arrow-right", // 向右箭头
  "rk:calculator": "gravity-ui:calculator", // 计算器
  "rk:folder-open": "lucide:folder-open-dot", // 打开文件夹
  "rk:call": "lucide:phone-call",
  "rk:sms": "lucide:message-square-text", // 短信
  "rk:system": "icon-park-outline:system", // 系统
  "rk:view": "lucide:eye", // 查看
  "rk:home": "gravity-ui:house", // 首页
  "rk:logo-r": "mynaui:letter-r-square", // LOGO-R
}
