export const RAKIT_ICONS = {
  "kit:user": "lucide:user-round", // 用户
  "kit:user-xmark": "lucide:user-round-x", // 用户x
  "kit:user-check": "lucide:user-round-check", // 用户check
  "kit:lock": "gravity-ui:lock", // 密码
  "kit:key": "lucide:key", // 密钥
  "kit:captcha": "gravity-ui:square-brackets-letter-a", // 验证码
  "kit:screen-full": "icon-park-outline:screenshot-one", // 全屏
  "kit:screen-exit": "icon-park-outline:off-screen", // 全屏
  "kit:sun": "lucide:sun", // 白天
  "kit:moon": "lucide:moon", // 夜晚
  "kit:bell": "lucide:bell-ring", // 铃铛/消息
  "kit:workbench": "icon-park-outline:workbench", // 工作台
  "kit:column-3": "lucide:columns-3", // 三列
  "kit:column-todo": "lucide:list-todo", // 设置
  "kit:column-density": "tabler:layout-distribute-horizontal", // 列设置
  "kit:xmark": "gravity-ui:xmark", // 叉号
  "kit:refresh": "gravity-ui:arrow-rotate-right", // 刷新
  "kit:sort-dots": "lucide:grip-vertical", // 排序
  "kit:upload": "lucide:upload", // 上传
  "kit:download": "lucide:download", // 上传
  "kit:export": "lucide:export", // 上传
  "kit:edit": "lucide:edit", // 编辑
  "kit:search": "lucide:search", // 搜索
  "kit:trash": "lucide:trash-2", // 删除
  "kit:plus": "lucide:plus", // 新增
  "kit:recycle": "tabler:recycle", // 回收
  "kit:history": "icon-park-outline:history-query", // 历史
  "kit:menu-left": "line-md:menu-fold-left", // 菜单左折叠
  "kit:menu-right": "line-md:menu-fold-right", // 菜单右折叠
  "kit:setting": "gravity-ui:nut-hex", // 设置
  "kit:logout": "si:sign-out-fill", // 退出
  "kit:play": "gravity-ui:play", // 播放
  "kit:pause": "gravity-ui:pause", // 暂停
  "kit:report": "tabler:report-analytics", // 报告
  "kit:score-100": "fluent:document-100-16-regular", // 100分
  "kit:chevron-up": "lucide:chevron-up", // 向上箭头
  "kit:chevron-down": "lucide:chevron-down", // 向下箭头
  "kit:chevron-left": "lucide:chevron-left", // 向左箭头
  "kit:chevron-right": "lucide:chevron-right", // 向右箭
  "kit:arrow-up": "lucide:arrow-up", // 向上箭头
  "kit:arrow-down": "lucide:arrow-down", // 向下箭头
  "kit:arrow-left": "lucide:arrow-left", // 向左箭头
  "kit:arrow-right": "lucide:arrow-right", // 向右箭头
  "kit:calculator": "gravity-ui:calculator", // 计算器
  "kit:folder-open": "lucide:folder-open-dot", // 打开文件夹
  "kit:call": "lucide:phone-call",
  "kit:sms": "lucide:message-square-text", // 短信
  "kit:system": "icon-park-outline:system", // 系统
  "kit:view": "lucide:eye", // 查看
  "kit:home": "gravity-ui:house", // 首页
}
