export const RAKIT_ICONS = {
  "ra:user": "lucide:user-round", // 用户
  "ra:user-xmark": "lucide:user-round-x", // 用户x
  "ra:user-check": "lucide:user-round-check", // 用户check
  "ra:lock": "gravity-ui:lock", // 密码
  "ra:key": "lucide:key", // 密钥
  "ra:captcha": "gravity-ui:square-brackets-letter-a", // 验证码
  "ra:screen-full": "icon-park-outline:screenshot-one", // 全屏
  "ra:screen-exit": "icon-park-outline:off-screen", // 全屏
  "ra:sun": "lucide:sun", // 白天
  "ra:moon": "lucide:moon", // 夜晚
  "ra:bell": "lucide:bell-ring", // 铃铛/消息
  "ra:workbench": "icon-park-outline:workbench", // 工作台
  "ra:column-3": "lucide:columns-3", // 三列
  "ra:column-todo": "lucide:list-todo", // 设置
  "ra:column-density": "tabler:layout-distribute-horizontal", // 列设置
  "ra:xmark": "gravity-ui:xmark", // 叉号
  "ra:refresh": "gravity-ui:arrow-rotate-right", // 刷新
  "ra:sort-dots": "lucide:grip-vertical", // 排序
  "ra:upload": "lucide:upload", // 上传
  "ra:download": "lucide:download", // 上传
  "ra:export": "lucide:export", // 上传
  "ra:edit": "lucide:edit", // 编辑
  "ra:search": "lucide:search", // 搜索
  "ra:trash": "lucide:trash-2", // 删除
  "ra:plus": "lucide:plus", // 新增
  "ra:recycle": "tabler:recycle", // 回收
  "ra:history": "icon-park-outline:history-query", // 历史
  "ra:menu-left": "line-md:menu-fold-left", // 菜单左折叠
  "ra:menu-right": "line-md:menu-fold-right", // 菜单右折叠
  "ra:setting": "gravity-ui:nut-hex", // 设置
  "ra:logout": "si:sign-out-fill", // 退出
  "ra:play": "gravity-ui:play", // 播放
  "ra:pause": "gravity-ui:pause", // 暂停
  "ra:report": "tabler:report-analytics", // 报告
  "ra:score-100": "fluent:document-100-16-regular", // 100分
  "ra:chevron-up": "lucide:chevron-up", // 向上箭头
  "ra:chevron-down": "lucide:chevron-down", // 向下箭头
  "ra:chevron-left": "lucide:chevron-left", // 向左箭头
  "ra:chevron-right": "lucide:chevron-right", // 向右箭
  "ra:arrow-up": "lucide:arrow-up", // 向上箭头
  "ra:arrow-down": "lucide:arrow-down", // 向下箭头
  "ra:arrow-left": "lucide:arrow-left", // 向左箭头
  "ra:arrow-right": "lucide:arrow-right", // 向右箭头
  "ra:calculator": "gravity-ui:calculator", // 计算器
  "ra:folder-open": "lucide:folder-open-dot", // 打开文件夹
  "ra:call": "lucide:phone-call",
  "ra:sms": "lucide:message-square-text", // 短信
  "ra:system": "icon-park-outline:system", // 系统
  "ra:view": "lucide:eye", // 查看
  "ra:home": "gravity-ui:house", // 首页
}
